"""Fair generalizations of Rock-Paper-Scissors."""

from .cache import CACHE_DIR, cached, load, save
from .display import letter_labels, pretty, show, wtl_labels
from .equilibrium import (
    equilibrium,
    equilibrium_dim,
    equilibrium_info,
    equilibrium_vertices,
    has_fully_mixed,
    kernel_dim,
    max_entropy_equilibrium,
    maxmin_equilibrium,
    num_equilibria,
)
from .generate import count_iso_classes, search_two_paradox
from .metrics import (
    aut_size,
    automorphisms,
    gini,
    node_orbits,
    num_cuts,
    num_orbits,
    num_roles,
    tie_fraction,
)
from .modular import (
    is_module,
    is_prime,
    modular_decomposition,
    named_subgame,
    neq_tree,
    tree_summary,
)
from .plot import CMAP, NORM, add_colorbar, best_layout, draw, equilibria_grid, grid, plot_modular
from .search import search_balanced, search_balanced_fast, search_inclusive, search_regular
from .structure import (
    canonical_key,
    canonicalize,
    connected,
    k_paradoxical,
    matrix_hash,
    orbit_hashes,
    paradoxical,
    profile_of,
    reduce_twins,
    regular,
    twin_free,
)

__all__ = [
    "CACHE_DIR",
    "CMAP",
    "NORM",
    "add_colorbar",
    "aut_size",
    "automorphisms",
    "best_layout",
    "cached",
    "canonical_key",
    "canonicalize",
    "connected",
    "count_iso_classes",
    "draw",
    "equilibria_grid",
    "equilibrium",
    "equilibrium_dim",
    "equilibrium_info",
    "equilibrium_vertices",
    "gini",
    "grid",
    "has_fully_mixed",
    "is_module",
    "is_prime",
    "k_paradoxical",
    "kernel_dim",
    "letter_labels",
    "load",
    "matrix_hash",
    "max_entropy_equilibrium",
    "maxmin_equilibrium",
    "modular_decomposition",
    "named_subgame",
    "neq_tree",
    "node_orbits",
    "num_cuts",
    "num_equilibria",
    "num_orbits",
    "num_roles",
    "orbit_hashes",
    "paradoxical",
    "plot_modular",
    "pretty",
    "profile_of",
    "reduce_twins",
    "regular",
    "save",
    "search_balanced",
    "search_balanced_fast",
    "search_inclusive",
    "search_regular",
    "search_two_paradox",
    "show",
    "tie_fraction",
    "tree_summary",
    "twin_free",
    "wtl_labels",
]
