"""Fair generalizations of Rock-Paper-Scissors."""

from .cache import CACHE_DIR, cached, load, save
from .display import letter_labels, pretty, show, wtl_labels
from .equilibrium import (
    equilibrium,
    equilibrium_info,
    has_fully_mixed,
    kernel_dim,
    max_entropy_equilibrium,
    maxmin_equilibrium,
)
from .metrics import (
    aut_size,
    automorphisms,
    gini,
    node_orbits,
    num_cuts,
    num_orbits,
    num_roles,
    tie_fraction,
)
from .plot import CMAP, NORM, add_colorbar, best_layout, draw, grid
from .search import search_balanced, search_balanced_fast, search_inclusive, search_regular
from .structure import (
    canonical_key,
    canonicalize,
    connected,
    k_paradoxical,
    matrix_hash,
    orbit_bytes,
    orbit_hashes,
    paradoxical,
    profile_of,
    reduce_twins,
    regular,
    twin_free,
)

__all__ = [
    "CACHE_DIR",
    "CMAP",
    "NORM",
    "add_colorbar",
    "aut_size",
    "automorphisms",
    "best_layout",
    "cached",
    "canonical_key",
    "canonicalize",
    "connected",
    "draw",
    "equilibrium",
    "equilibrium_info",
    "gini",
    "grid",
    "has_fully_mixed",
    "k_paradoxical",
    "kernel_dim",
    "letter_labels",
    "load",
    "matrix_hash",
    "max_entropy_equilibrium",
    "maxmin_equilibrium",
    "node_orbits",
    "num_cuts",
    "num_orbits",
    "num_roles",
    "orbit_bytes",
    "orbit_hashes",
    "paradoxical",
    "pretty",
    "profile_of",
    "reduce_twins",
    "regular",
    "save",
    "search_balanced",
    "search_balanced_fast",
    "search_inclusive",
    "search_regular",
    "show",
    "tie_fraction",
    "twin_free",
    "wtl_labels",
]
